version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: saudi_hr_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123 # TODO: Change for production
      POSTGRES_DB: saudi_hr_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: saudi_hr_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
